# Generated by Django 4.0.5 on 2022-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
