# Generated by Django 4.0.5 on 2022-06-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_remove_product_expiration_date_alter_history_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
