# Generated by Django 4.0.3 on 2022-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_remove_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='add_quantity',
        ),
        migrations.RemoveField(
            model_name='history',
            name='expired_quantity',
        ),
        migrations.RemoveField(
            model_name='history',
            name='inventory_quantity',
        ),
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(0, 'Add quantity'), (1, 'Expired quantity'), (2, 'Inventory quantity')], default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
