# Generated by Django 4.0.5 on 2022-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transition',
            new_name='Transaction',
        ),
    ]
