# Generated by Django 4.0.5 on 2022-06-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0002_rename_transition_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
