# Generated by Django 4.0.3 on 2022-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0005_transaction_created_at_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_choices',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Revenue')], default=0),
        ),
    ]
