# Generated by Django 4.0.3 on 2022-07-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0006_category_class_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='class_choices',
        ),
    ]
