# Generated by Django 4.0.3 on 2022-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0007_remove_category_class_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_choices',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Revenue')], default=0),
        ),
    ]
