# Generated by Django 4.0.3 on 2022-07-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0008_category_category_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choices',
        ),
    ]
