# Generated by Django 4.0.3 on 2022-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0009_remove_category_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_choices',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Revenue')], default=0),
        ),
    ]
